#!/bin/bash

# IMMEDIATE FIX: Copy this cookies content to your server

echo "🍪 IMMEDIATE COOKIE FIX FOR YOUR SERVER"
echo "======================================"
echo ""
echo "STEP 1: Copy the cookies content below:"
echo "========================================="

cat << 'EOF'
# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com	TRUE	/	FALSE	0	PREF	hl=en&tz=UTC
.youtube.com	TRUE	/	TRUE	0	SOCS	CAI
.youtube.com	TRUE	/	TRUE	1757155300	GPS	1
.youtube.com	TRUE	/	TRUE	0	YSC	K5Y5tSKvwr8
.youtube.com	TRUE	/	TRUE	1772705501	__Secure-ROLLOUT_TOKEN	CIyX38yv27LSShDTub7x8sOPAxjbopvy8sOPAw%3D%3D
.youtube.com	TRUE	/	TRUE	1772705501	VISITOR_INFO1_LIVE	LXWPb1rbN_c
.youtube.com	TRUE	/	TRUE	1772705501	VISITOR_PRIVACY_METADATA	CgJJThIEGgAgNg%3D%3D
.youtube.com	TRUE	/	TRUE	1820225501	__Secure-YT_TVFAS	t=488098&s=2
.youtube.com	TRUE	/	TRUE	1772705501	DEVICE_INFO	ChxOelUwTmpreE5qZ3lNalUyTURBME9EZzFOZz09EN2R8MUGGN2R8MUG
.youtube.com	TRUE	/tv	TRUE	1789985501	__Secure-YT_DERP	CJrT7pFd
EOF

echo ""
echo "STEP 2: On your server, run these commands:"
echo "==========================================="
echo "ssh prasanth@209.74.95.163"
echo "cd /home/prasanth/ogplayer"
echo "nano youtube_cookies.txt"
echo "# Paste the cookies content above, then save with Ctrl+X, Y, Enter"
echo ""

echo "STEP 3: Test the fix:"
echo "===================="
echo "yt-dlp --cookies youtube_cookies.txt --get-title 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'"
echo ""
echo "STEP 4: Test your original command:"
echo "=================================="
echo "yt-dlp --cookies youtube_cookies.txt -f bestaudio -o - https://www.youtube.com/watch?v=-WVDfHUVym4"
echo ""

echo "STEP 5: Start your updated server:"
echo "=================================="
echo "node simple-server.js"
echo ""

echo "✅ This should fix the 'Sign in to confirm you're not a bot' error!"
echo ""
echo "🌐 Or use the web interface: http://209.74.95.163:3001/cookies.html"
